chenyiwenglish.hamq:
  autoconfigure:
    enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/hamq?autoReconnect=true
    username: root
    password: 123123
  idc: sh
  queue:
    test.queue-id: 1
